/**
 * M2 — Marques avec lesquelles le magasin travaille (suggestions du champ
 * « Marque » des fiches articles — saisie libre conservée pour les nouvelles).
 */
export const PARTNER_BRANDS: string[] = [
  '13.8 COMPOSITES', 'AFAM', 'AGV', 'AKRAPOVIC', 'ALPINESTARS', 'APRILIA', 'ARAI',
  'ARROW', 'BARDAHL', 'BARRACUDA', 'BEEPINGS', 'BIHR', 'BIKE-LIFT', 'BONAMICI',
  'BREMBO', 'BWT', 'CANDICAR', 'CARBONVANI', 'CARDO', 'CASTROL', 'CHIGEE', 'CNC',
  'COYOTE SYSTEMS', 'D.I.D', "DELL'ORTO", 'DUCATI', 'DUCATI BXL', 'DUCATI SPACERS',
  'EVOTECH PERFORMANCE', 'GARMIN', 'GB RACING', 'GUBELLINI', 'HPX', 'ILMBERGER',
  'IMA', 'INNOTEC', 'IPONE', 'IRC', 'JETPRIME', 'KITCROSS', 'LIGHTECH', 'MARCHESINI',
  'MATTHYS', 'MELOTTI', 'METZELER', 'MITAS', 'MOSA FREIN', 'MOTO-MASTER',
  'MOTOHOLDERS', 'MOTUL', 'N-COM', 'NGK', 'NULON', 'OHLINS', 'OPTIMATE', 'OXFORD',
  'OZ', 'PERFORMANCE TECHNOLOGY', 'PIEROBON', 'PINLOCK', 'PIRELLI', 'PROGRIP',
  'PZ RACING', 'R&G', 'RAM-MOUNTS', 'RED FOX', "REV'IT", 'RIZOMA', 'SC PROJECT',
  'SENA', 'SHELL', 'SITTA', 'SKF', 'SKYRICH', 'SP CONNECT', 'STM', 'SW-MOTECH',
  'TECHRACE', 'TERMIGNONI', 'VULCANET', 'VULTURBIKE', 'WEEKEND PRODUCTS', 'YUASA',
];
